version: "3.9"
services:
  frontend:
    container_name: attack-workbench-frontend
    build: .
    depends_on:
      - rest-api
      - collection-manager
    ports:
      - "80:80"
    volumes:
      - ./docker-compose-resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  rest-api:
    container_name: attack-workbench-rest-api
    build: ../attack-workbench-rest-api
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./docker-compose-resources/rest-api/rest-api-service-config.json:/usr/src/app/resources/rest-api-service-config.json:ro
    environment:
      - DATABASE_URL=mongodb://attack-workbench-database/attack-workspace
      - SERVICE_ACCOUNT_APIKEY_ENABLE=true
      - JSON_CONFIG_PATH=./resources/rest-api-service-config.json

  collection-manager:
    container_name: attack-workbench-collection-manager
    build: ../attack-workbench-collection-manager
    depends_on:
      - rest-api
    ports:
      - "3001:3001"
    environment:
      - WORKBENCH_HOST=http://attack-workbench-rest-api
      - WORKBENCH_AUTHN_SERVICE_NAME=collection-manager
      - WORKBENCH_AUTHN_APIKEY=sample-key

  mongodb:
    container_name: attack-workbench-database
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  db-data:
