# Description
# - This file augments the deployment of the ATT&CK Workbench by configuring the collection-manager container
# - with an additional certificate.
# - This is recommended for deployments where the collection-manager container is behind a firewall that performs
#   SSL inspection. The additional certificate allows collection-manager to retrieve collection-indexes and
#   collection bundles without receiving a self-signed certificate error.

# Usage
# This file must be used in conjunction with the main docker-compose.yml file.
#
# Environment Variables
# HOST_CERTS_PATH: path to the directory on the host where the certificate file is located
# CERTS_FILENAME: certs/MITRE-chain.txt
#
# Running docker compose at the command line:
# docker-compose -f docker-compose.yml -f docker-compose.certs.yml up

version: "3.9"
services:
  rest-api:
    volumes:
      - ./certs:/usr/src/app/certs
    environment:
      - NODE_EXTRA_CA_CERTS=./certs/MITRE-chain.txt
